# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - 'charts/**'
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      -
        name: Generate a Docker image tag
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/v'* ]]; then
            TAGS='["lindseyvolk/examplepostapp-modernized:latest","lindseyvolk/examplepostapp-modernized:'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["lindseyvolk/examplepostapp-modernized:latest"]'
          fi
          echo "::set-output name=tags::$TAGS"
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
